--- #YAML:1.0
name:                Crypt-MatrixSSL
version:             1.86
abstract:            Perl extension for SSL and TLS using MatrixSSL.org 
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - C. N. Drake <christopher@pobox.com>
